name: Backend Auto Deploy to EC2

on:
  push:
    branches:
      - dev
      - feat/deploy/#28

jobs:
  Deploy_Backend_to_EC2:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 서버에 SSH 원격 접속 후 자동 배포 작업 수행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/local-community-web
            git pull origin dev
            cd backend
            sudo rm -rf src/main/test
            sudo rm -rf src/main/resources/application.properties
            echo "${{ secrets.APPLICATION_PROPERTIES }}" | sudo tee /home/ubuntu/local-community-web/backend/src/main/resources/application.properties > /dev/null
            cat /home/ubuntu/local-community-web/backend/src/main/resources/application.properties  # 생성된 파일 내용 확인
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &