# Workflow 이름
name: Backend Auto Deploy to EC2

# Event(실행되는 시점을 설정)
# dev 브랜치에 push 될 때 아래 Workflow 실행
on:
  push:
    branches:
      - dev

# Workflow Job(병렬 수행)
jobs:
  # Job 이름
  Deploy_Backend_to_EC2:
    # OS
    runs-on: ubuntu-latest

    # Job Step
    steps:
      - name: EC2 서버에 SSH 원격 접속 후 자동 배포 작업 수행
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stops: true
          script: |
            cd /home/ubuntu/local-community-web
            git pull origin dev
            cd backend
            rm -rf src/main/test
            rm -rf src/main/resources/application.properties
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
